import type { RouteDefinition, Section } from "../types";
import {
  accommodationDoc,
  admissionFacts,
  bankStatementDoc,
  employmentLetterDoc,
  employmentSection,
  financesSection,
  homeTiesSection,
  identitySection,
  invitationDoc,
  itineraryDoc,
  passportDoc,
  payslipsDoc,
  refusalLetterDoc,
  refusalsSection,
  sponsorEvidenceDoc,
  sponsorSection,
  studySection,
  travelHistorySection,
  tripSection,
} from "./shared";

const SHARED_CHECKS = [
  "name_match",
  "salary_triangulation",
  "passport_validity",
  "funds_vs_cost",
  "large_deposit",
  "sponsor_capacity",
  "refusal_explanation",
  "employment_leave",
];

const usRelativesSection: Section = {
  id: "us_relatives",
  title: "Connections in the United States",
  questions: [
    { id: "us.has_relatives", label: "Do you have immediate family in the United States?", type: "boolean", required: true, help: "This must match your DS-160 and any invitation letter." },
    { id: "us.relatives_detail", label: "Who, and what is their status?", type: "textarea", showIf: { questionId: "us.has_relatives", equals: true } },
    { id: "us.previous_travel", label: "Have you travelled to the U.S. before?", type: "boolean", required: true },
  ],
};

export const US_B1B2: RouteDefinition = {
  id: "US_B1B2",
  kind: "visitor",
  country: "US",
  countryName: "United States",
  name: "United States — B1/B2 Visitor Visa",
  shortName: "US B1/B2 Visitor",
  tagline: "Business and tourism visits to the United States",
  sections: [
    identitySection,
    tripSection("the United States"),
    employmentSection,
    financesSection,
    sponsorSection,
    usRelativesSection,
    travelHistorySection,
    refusalsSection,
    homeTiesSection,
  ],
  documents: [
    passportDoc,
    {
      type: "ds160_evidence",
      label: "DS-160 confirmation / screenshots",
      requirement: "recommended",
      categories: ["consistency"],
      help: "Screenshots of your DS-160 answers let the assessment check them against your evidence.",
    },
    employmentLetterDoc(["employment", "home_ties"]),
    payslipsDoc(["financial", "employment"]),
    bankStatementDoc(["financial"]),
    invitationDoc(["purpose", "consistency"]),
    sponsorEvidenceDoc(["financial", "purpose"]),
    itineraryDoc(["purpose"]),
    accommodationDoc(["purpose"]),
    refusalLetterDoc,
  ],
  categories: [
    { id: "purpose", label: "Purpose of Visit", weight: 0.15, sections: ["trip"] },
    { id: "financial", label: "Financial Capacity", weight: 0.18, sections: ["finances"] },
    { id: "employment", label: "Employment & Economic Circumstances", weight: 0.14, sections: ["employment"] },
    { id: "home_ties", label: "Family & Home Ties", weight: 0.16, sections: ["home_ties", "us_relatives"] },
    { id: "travel_history", label: "Travel History", weight: 0.1, sections: ["travel_history"] },
    { id: "consistency", label: "Application Consistency", weight: 0.15 },
    { id: "documentation", label: "Documentation", weight: 0.07, sections: ["identity"] },
    { id: "previous_refusals", label: "Previous Refusals", weight: 0.05, sections: ["refusals"] },
  ],
  checks: [...SHARED_CHECKS, "invitation_duration", "us_relatives_contradiction"],
  interview: true,
};

export const US_F1: RouteDefinition = {
  id: "US_F1",
  kind: "study",
  country: "US",
  countryName: "United States",
  name: "United States — F-1 Student Visa",
  shortName: "US F-1 Student",
  tagline: "Full-time study in the United States",
  sections: [
    identitySection,
    studySection,
    employmentSection,
    financesSection,
    sponsorSection,
    usRelativesSection,
    travelHistorySection,
    refusalsSection,
    homeTiesSection,
  ],
  documents: [
    passportDoc,
    {
      type: "i20",
      label: "Form I-20",
      requirement: "required",
      categories: ["school", "consistency"],
      factFields: [
        { id: "identity.full_name", label: "Student name on the I-20", type: "text" },
        { id: "study.institution", label: "Institution on the I-20", type: "text" },
        { id: "study.programme", label: "Programme on the I-20", type: "text" },
        { id: "study.start_date", label: "Start date on the I-20", type: "date" },
        { id: "i20.total_cost_year1", label: "Estimated first-year cost on the I-20", type: "money" },
        { id: "i20.personal_funds", label: "Personal funds shown on the I-20", type: "money" },
        { id: "i20.school_funding", label: "School funding shown on the I-20", type: "money" },
      ],
    },
    {
      type: "admission_letter",
      label: "Admission letter",
      requirement: "required",
      categories: ["school"],
      factFields: admissionFacts,
    },
    { type: "ds160_evidence", label: "DS-160 confirmation / screenshots", requirement: "recommended", categories: ["consistency"] },
    bankStatementDoc(["financial", "funding"]),
    sponsorEvidenceDoc(["financial", "funding"]),
    { type: "transcripts", label: "Academic transcripts & certificates", requirement: "required", categories: ["academic"] },
    { type: "test_results", label: "Test results (English / standardized), if any", requirement: "recommended", categories: ["academic"] },
    { type: "sevis_receipt", label: "SEVIS I-901 fee receipt", requirement: "recommended", categories: ["documentation"] },
    refusalLetterDoc,
  ],
  categories: [
    { id: "school", label: "School Documentation", weight: 0.12, sections: ["study"] },
    { id: "financial", label: "Financial Capacity", weight: 0.16, sections: ["finances"] },
    { id: "funding", label: "Funding Source", weight: 0.12, sections: ["sponsor"] },
    { id: "academic", label: "Academic Progression & Programme Logic", weight: 0.14, sections: ["study"] },
    { id: "home_ties", label: "Ties Home & Temporary Intent", weight: 0.14, sections: ["home_ties", "us_relatives"] },
    { id: "consistency", label: "Application Consistency", weight: 0.15 },
    { id: "documentation", label: "Documentation", weight: 0.07, sections: ["identity"] },
    { id: "previous_refusals", label: "Previous Refusals", weight: 0.05, sections: ["refusals"] },
    { id: "employment", label: "Employment History", weight: 0.05, sections: ["employment"] },
  ],
  checks: [...SHARED_CHECKS, "study_funding_gap", "i20_consistency", "academic_logic", "us_relatives_contradiction"],
  interview: true,
};

export const CA_TRV: RouteDefinition = {
  id: "CA_TRV",
  kind: "visitor",
  country: "CA",
  countryName: "Canada",
  name: "Canada — Visitor Visa (Temporary Resident Visa)",
  shortName: "Canada Visitor",
  tagline: "Visiting Canada for tourism, family or business",
  sections: [
    identitySection,
    tripSection("Canada"),
    employmentSection,
    financesSection,
    sponsorSection,
    travelHistorySection,
    refusalsSection,
    homeTiesSection,
  ],
  documents: [
    passportDoc,
    employmentLetterDoc(["employment", "home_ties"]),
    payslipsDoc(["financial", "employment"]),
    bankStatementDoc(["financial"]),
    invitationDoc(["purpose", "consistency"]),
    sponsorEvidenceDoc(["financial", "purpose"]),
    itineraryDoc(["purpose"]),
    accommodationDoc(["purpose"]),
    refusalLetterDoc,
  ],
  categories: [
    { id: "purpose", label: "Purpose of Visit", weight: 0.15, sections: ["trip"] },
    { id: "financial", label: "Financial Capacity", weight: 0.18, sections: ["finances"] },
    { id: "employment", label: "Employment & Economic Circumstances", weight: 0.14, sections: ["employment"] },
    { id: "home_ties", label: "Family & Home Ties", weight: 0.16, sections: ["home_ties"] },
    { id: "travel_history", label: "Travel History", weight: 0.1, sections: ["travel_history"] },
    { id: "consistency", label: "Application Consistency", weight: 0.15 },
    { id: "documentation", label: "Documentation", weight: 0.07, sections: ["identity"] },
    { id: "previous_refusals", label: "Previous Refusals", weight: 0.05, sections: ["refusals"] },
  ],
  checks: [...SHARED_CHECKS, "invitation_duration"],
  interview: false,
};

const caStudyExtras: Section = {
  id: "ca_study",
  title: "Canada study details",
  questions: [
    { id: "ca.province", label: "Province of study", type: "select", required: true, options: [
      { value: "ON", label: "Ontario" }, { value: "BC", label: "British Columbia" },
      { value: "QC", label: "Québec" }, { value: "AB", label: "Alberta" },
      { value: "MB", label: "Manitoba" }, { value: "SK", label: "Saskatchewan" },
      { value: "NS", label: "Nova Scotia" }, { value: "NB", label: "New Brunswick" },
      { value: "NL", label: "Newfoundland and Labrador" }, { value: "PE", label: "Prince Edward Island" },
      { value: "OTHER", label: "Territories / other" },
    ] },
    { id: "ca.tuition_paid", label: "Tuition already paid", type: "money" },
    { id: "ca.needs_pal", label: "Does your study level require a Provincial/Territorial Attestation Letter (PAL/TAL)?", type: "boolean", help: "Most undergraduate and college programmes need one; check with your institution." },
  ],
};

export const CA_STUDY: RouteDefinition = {
  id: "CA_STUDY",
  kind: "study",
  country: "CA",
  countryName: "Canada",
  name: "Canada — Study Permit",
  shortName: "Canada Study Permit",
  tagline: "Studying at a Canadian designated learning institution",
  sections: [
    identitySection,
    studySection,
    caStudyExtras,
    employmentSection,
    financesSection,
    sponsorSection,
    travelHistorySection,
    refusalsSection,
    homeTiesSection,
  ],
  documents: [
    passportDoc,
    {
      type: "loa",
      label: "Letter of Acceptance (LOA)",
      requirement: "required",
      categories: ["admission"],
      factFields: admissionFacts,
    },
    {
      type: "pal",
      label: "Provincial/Territorial Attestation Letter (PAL/TAL)",
      requirement: "conditional",
      condition: { questionId: "ca.needs_pal", equals: true },
      categories: ["admission"],
    },
    {
      type: "caq",
      label: "CAQ (Québec only)",
      requirement: "conditional",
      condition: { questionId: "ca.province", equals: "QC" },
      categories: ["admission"],
    },
    { type: "tuition_receipt", label: "Tuition payment receipt", requirement: "recommended", categories: ["funding"] },
    bankStatementDoc(["financial", "funding"]),
    sponsorEvidenceDoc(["financial", "funding"]),
    { type: "transcripts", label: "Academic transcripts & certificates", requirement: "required", categories: ["academic"] },
    { type: "study_plan", label: "Study plan / Letter of Explanation", requirement: "recommended", categories: ["academic", "purpose"], help: "Why this programme, this institution, and Canada — and your plans after." },
    employmentLetterDoc(["home_ties"]),
    refusalLetterDoc,
  ],
  categories: [
    { id: "admission", label: "Admission Evidence (LOA / PAL / CAQ)", weight: 0.14, sections: ["study", "ca_study"] },
    { id: "financial", label: "Financial Capacity", weight: 0.16, sections: ["finances"] },
    { id: "funding", label: "Funding Source", weight: 0.12, sections: ["sponsor"] },
    { id: "academic", label: "Academic Progression & Study Purpose", weight: 0.14, sections: ["study"] },
    { id: "home_ties", label: "Home-Country Circumstances", weight: 0.14, sections: ["home_ties"] },
    { id: "consistency", label: "Application Consistency", weight: 0.15 },
    { id: "documentation", label: "Documentation", weight: 0.05, sections: ["identity"] },
    { id: "previous_refusals", label: "Previous Refusal Risk", weight: 0.05, sections: ["refusals"] },
    { id: "purpose", label: "Study Purpose", weight: 0.05, sections: ["study"] },
  ],
  checks: [...SHARED_CHECKS, "study_funding_gap", "ca_living_funds", "academic_logic"],
  interview: false,
};

export const UK_VISITOR: RouteDefinition = {
  id: "UK_VISITOR",
  kind: "visitor",
  country: "GB",
  countryName: "United Kingdom",
  name: "United Kingdom — Standard Visitor Visa",
  shortName: "UK Standard Visitor",
  tagline: "Visiting the UK for tourism, family or business",
  sections: [
    identitySection,
    tripSection("the United Kingdom"),
    employmentSection,
    financesSection,
    sponsorSection,
    travelHistorySection,
    refusalsSection,
    homeTiesSection,
  ],
  documents: [
    passportDoc,
    employmentLetterDoc(["employment", "home_ties"]),
    payslipsDoc(["financial", "employment"]),
    bankStatementDoc(["financial"]),
    invitationDoc(["purpose", "consistency"]),
    sponsorEvidenceDoc(["financial", "purpose"]),
    itineraryDoc(["purpose"]),
    accommodationDoc(["purpose"]),
    refusalLetterDoc,
  ],
  categories: [
    { id: "purpose", label: "Purpose of Visit", weight: 0.15, sections: ["trip"] },
    { id: "financial", label: "Financial Evidence", weight: 0.18, sections: ["finances"] },
    { id: "employment", label: "Employment", weight: 0.14, sections: ["employment"] },
    { id: "home_ties", label: "Home Circumstances", weight: 0.16, sections: ["home_ties"] },
    { id: "travel_history", label: "Travel History", weight: 0.1, sections: ["travel_history"] },
    { id: "consistency", label: "Application Consistency", weight: 0.15 },
    { id: "documentation", label: "Documentation", weight: 0.07, sections: ["identity"] },
    { id: "previous_refusals", label: "Previous Refusal Risk", weight: 0.05, sections: ["refusals"] },
  ],
  checks: [...SHARED_CHECKS, "invitation_duration", "uk_duration_limit"],
  interview: false,
};

export const ROUTES: RouteDefinition[] = [US_B1B2, US_F1, CA_TRV, CA_STUDY, UK_VISITOR];

export function getRoute(id: string): RouteDefinition | undefined {
  return ROUTES.find((r) => r.id === id);
}
